repos:
-   repo: https://github.com/PyCQA/flake8
    rev: '7.0.0'
    hooks:
    -   id: flake8
        args: ['--max-line-length=160', '--exclude=.venv']
        language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: debug-statements
        language_version: python3

-   repo: https://github.com/pycqa/pydocstyle
    rev: '6.3.0'
    hooks:
    -   id: pydocstyle
        args: ['--convention=google', '--add-ignore=D100,D101,D102,D103,D104,D105,D106,D107']

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/hhatto/autopep8
    rev: v2.1.0
    hooks:
    -   id: autopep8
